spring.application.name=Restoran-Management-System

# MySQL connection
spring.datasource.url=jdbc:mysql://localhost:3306/restaurant?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=revan123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# --- JWT Configuration ---
jwt.secret=amdks-asdnasfn-dasda-as-asder-32-bwehcwj123-dawfd
jwt.expiration=3600000